import type { DbTable, DbEdge, RelationshipType } from '../types/database'
import { FIELD_TYPE_LABELS } from '../types/database'

// ─── Маппинг типов ────────────────────────────────────────────

function mapType(type: string): string {
  return FIELD_TYPE_LABELS[type as keyof typeof FIELD_TYPE_LABELS] || type.toUpperCase()
}

// ─── Нотация связей (Crow's Foot) ──────────────────────────────

function getRelationshipNotation(type: RelationshipType): { source: string; target: string } {
  switch (type) {
    case 'one_to_one':
      return { source: '1', target: '1' }
    case 'one_to_many':
      return { source: '1', target: '<' }
    case 'many_to_many':
      return { source: '<', target: '<' }
  }
}

// ─── Генерация CREATE TABLE ───────────────────────────────────

function generateCreateTableSQL(table: DbTable): string {
  const columns = table.fields
    .map((field) => {
      const parts: string[] = []

      // Имя
      parts.push(`    ${field.name}`)

      // Тип
      parts.push(mapType(field.type))

      // PK
      if (field.isPrimaryKey) {
        parts.push('PRIMARY KEY')
      }

      // NOT NULL
      if (field.isNotNull && !field.isPrimaryKey) {
        parts.push('NOT NULL')
      }

      // AUTO_INCREMENT
      if (field.isAutoIncrement) {
        parts.push('AUTO_INCREMENT')
      }

      // DEFAULT
      if (field.defaultValue !== undefined && field.defaultValue !== '') {
        parts.push(`DEFAULT '${field.defaultValue}'`)
      }

      return parts.join(' ')
    })
    .join(',\n')

  return `CREATE TABLE ${table.name} (\n${columns}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`
}

// ─── Генерация полного SQL-скрипта ─────────────────────────────

export function generateSQL(tables: DbTable[], edges: DbEdge[]): string {
  const lines: string[] = []

  lines.push('-- ============================================')
  lines.push('-- Database Schema (auto-generated by DB Modeler)')
  lines.push(`-- Generated: ${new Date().toISOString()}`)
  lines.push('-- ============================================')
  lines.push('')

  // Строим карту зависимостей для правильного порядка CREATE TABLE
  const fieldToTable = new Map<string, string>()
  tables.forEach((t) => {
    t.fields.forEach((f) => fieldToTable.set(f.id, t.id))
  })

  const dependencies = new Map<string, Set<string>>()
  edges.forEach((e) => {
    if (!dependencies.has(e.targetTable)) {
      dependencies.set(e.targetTable, new Set())
    }
    dependencies.get(e.targetTable)!.add(e.sourceTable)
  })

  // Топологическая сортировка
  const sorted: string[] = []
  const visited = new Set<string>()

  function visit(tableId: string) {
    if (visited.has(tableId)) return
    visited.add(tableId)
    const deps = dependencies.get(tableId)
    deps?.forEach((dep) => visit(dep))
    sorted.push(tableId)
  }

  tables.forEach((t) => visit(t.id))

  // Генерируем CREATE TABLE
  sorted.forEach((tableId) => {
    const table = tables.find((t) => t.id === tableId)
    if (!table) return

    lines.push(generateCreateTableSQL(table))

    const tableEdges = edges.filter((e) => e.sourceTable === tableId)
    if (tableEdges.length > 0) {
      lines.push('')
      lines.push(`-- Foreign keys for ${table.name}`)
      tableEdges.forEach((edge, idx) => {
        const sourceTable = tables.find((t) => t.id === edge.sourceTable)
        const targetTable = tables.find((t) => t.id === edge.targetTable)
        const sourceField = sourceTable?.fields.find((f) => f.id === edge.source)
        const targetField = targetTable?.fields.find((f) => f.id === edge.target)

        if (sourceTable && sourceField && targetTable && targetField) {
          const fkName = `fk_${targetTable.name}_${sourceTable.name}_${idx}`
          lines.push(
            `ALTER TABLE ${targetTable.name}`
          )
          lines.push(
            `  ADD CONSTRAINT ${fkName}`
          )
          lines.push(
            `  FOREIGN KEY (${sourceField.name}) REFERENCES ${sourceTable.name}(${targetField.name})`
          )
          lines.push(`  ON DELETE CASCADE;`)
          lines.push('')
        }
      })
    }

    lines.push('')
  })

  // Добавляем визуальную нотацию связей в комментарии
  if (edges.length > 0) {
    lines.push('-- ============================================')
    lines.push('-- Relationships (Crow\'s Foot notation)')
    lines.push('-- ============================================')
    edges.forEach((edge) => {
      const notation = getRelationshipNotation(edge.relationshipType)
      const sourceTable = tables.find((t) => t.id === edge.sourceTable)
      const targetTable = tables.find((t) => t.id === edge.targetTable)
      const sourceField = sourceTable?.fields.find((f) => f.id === edge.source)
      const targetField = targetTable?.fields.find((f) => f.id === edge.target)

      if (sourceTable && targetTable && sourceField && targetField) {
        lines.push(
          `${sourceTable.name}.${sourceField.name} ${notation.source}───${notation.target} ${targetTable.name}.${targetField.name} [${edge.relationshipType}]`
        )
      }
    })
  }

  return lines.join('\n')
}

// ─── Экспорт в JSON ───────────────────────────────────────────

export function exportToJSON(tables: DbTable[], edges: DbEdge[]): string {
  return JSON.stringify({ tables, edges }, null, 2)
}

// ─── Импорт из JSON ───────────────────────────────────────────

export interface ImportedData {
  tables: DbTable[]
  edges: DbEdge[]
}

export function importFromJSON(json: string): ImportedData {
  return JSON.parse(json)
}
